# Generated by Django 4.0.5 on 2022-08-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_photo_gallery_photo_user_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
